### ISSUE TITLE
when i use this plugin some error in my theme options

### ISSUE THREAD

**Issue by Powerin10** [brainstormforce/all-in-one-schemaorg-rich-snippets#27]
when i use this plugin in my site 
some error not working my theme option properly...
if i deactive this plugin its working fine...

i sended a attach file console screen shot please solve it 👍 
![screenshot_1](https://cloud.githubusercontent.com/assets/10785280/22863246/7183eb8e-f166-11e6-806e-07aa880fa684.png)

**Comment by sandeshjangam** [comment]
Please updated the latest version 1.4.2 and let us know if it work for you or not?
