### ISSUE TITLE
Using the subject - people - breaks code 

### ISSUE THREAD

**Issue by afaitken** [brainstormforce/all-in-one-schemaorg-rich-snippets#28]
All selections work fine except "people" - using latest Wordpress with MH News theme. 
It has an extra "closed" </div> somewhere in the code causing the sidebar to move down below the main content.
Adding an open <div> at the end of the content (body of article) temporarily fixes the issue.
This proves there is an extra </div> in the people section of the code.

**Comment by afaitken** [comment]
FOUND! Remove one of the two first </div> on line 361 in functions.php

Then, problem fixed!

This needs to be updated in the next release please...

**Comment by sandeshjangam** [comment]
Issue is fixed in latest update 1.4.2.
