### ISSUE TITLE
name property

### ISSUE THREAD

**Issue by ChaMbuna** [brainstormforce/all-in-one-schemaorg-rich-snippets#3]
According to the Google Rich Snippet Testing Tool, the name property is missing from the rich snippet metadata. This is a required property. I've only tested this with Event and Product.
https://developers.google.com/structured-data/testing-tool/

**Comment by Nikschavan** [comment]
Hey @ChaMbuna, We have recently updated the plugin to version `1.3.0` which should have already fixed this issue, can you confirm if this issue is still relevant?

~ Nik
