### ISSUE TITLE
Rich Snippets appears ON my website when plugin is on

### ISSUE THREAD

**Issue by abridgedpause** [brainstormforce/all-in-one-schemaorg-rich-snippets#35]
I really want to use the Rich Snippet plugin and get the most out of Google. But when I activate the plugin, for some reason, the Rich Snippet actually appears ON my website, under the news posts. I took some print screens to show it.

Turned on http://prntscr.com/eoc1z9
Turned off http://prntscr.com/eoc33l

Is this normal? What could be causing this? Is there a work-around?

**Comment by Nikschavan** [comment]
Hello @abridgedpause 

Yes, that is how this is supposed to work. The plugin adds the required markup for the schema tags on your post, When google crawls your site it finds that schema markup and it uses it when displaying it in the search results.
