### ISSUE TITLE
var_dump in bsd_Meta_box causes problems

### ISSUE THREAD

**Issue by marcobax** [brainstormforce/all-in-one-schemaorg-rich-snippets#39]
On line 359 in the file all-in-one-schemaorg-rich-snippets/init.php there is a call to var_dump which causes the `save draft` functionality in Wordpress to break. This can be easily fixed by removing this var_dump($post_id).

**Comment by Nikschavan** [comment]
Thank you for pointing it out @marcobax, This is fixed in https://github.com/brainstormforce/all-in-one-schemaorg-rich-snippets/commit/49f12bfc717ccfdfe73315ee80d183ecc9391c17

**Comment by marcobax** [comment]
Amazing, thank you for fixing it so soon!
