### ISSUE TITLE
How can I hide the summary box on the content?

### ISSUE THREAD

**Issue by evilninjas** [brainstormforce/all-in-one-schemaorg-rich-snippets#63]
How can we have the summary box disappear? So, it does not appear to visitors?

**Comment by UttamSharma007** [comment]
It is compulsory to show microdata markup on the page. If the markup is hidden then Google will not consider these hidden markups in the google search result.
Please refer this screenshot:
https://goo.gl/WU7wcT
Refer these articles:
https://stackoverflow.com/questions/8903526/is-it-ok-to-hide-microdata-with-css/21751532
https://schema.org/docs/gs.html#schemaorg_expected
https://stackoverflow.com/questions/16336655/how-to-hide-microdata-schema

Hope it clarifies you!

**Comment by evilninjas** [comment]
But does it need to have the box though shown on the front side? As long as it is shown in the source code, Google will still find the mark-ups.

**Comment by UttamSharma007** [comment]
If you wish to hide the summary box in the frontend, add this custom CSS on your site:-
#snippet-box {
  display: none !important;
}

**Comment by kvsc** [comment]
Thanks for the resolving the issue.
