### ISSUE TITLE
import some data from yoast seo

### ISSUE THREAD

**Issue by sabinich** [brainstormforce/all-in-one-schemaorg-rich-snippets#83]
Very booooooring typing to field  info about link to image, description or whatever twice, i guess. Maybe do it automatically?
anyway thank for your plugin ;)

**Comment by Nikschavan** [comment]
Hello @sabinich, You can check out [Schema Pro](https://wpschema.com/) which lets you configure the schema configurations once and make it work on all the posts.

Reading the data from Yoast SEO as well with this plugin.
