### ISSUE TITLE
wp.media.editor fails to load on backend, breaking js

### ISSUE THREAD

**Issue by riconeitzel** [brainstormforce/all-in-one-schemaorg-rich-snippets#9]
Hi there,

if you have additional backend packes running javascript a weird issue appears:

```
TypeError: undefined is not an object (evaluating 'wp.media.editor')
```

If you disable your plugin everthing's going back to normal.

Testing with: WordPress 4.1.1 + Custom Field Suite + yours -> Custom Field Suite Backend breaks (adding fields doesn't work anymore) as longs as you plugin is active

**Comment by JoelStickney** [comment]
Having the same issue, but with ACF.

**Comment by djsheva** [comment]
@Nikschavan pull request #50 should fix this
